name: Android CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
  
#     - uses: nttld/setup-ndk@v1
#       with:
#        ndk-version: r22b

    - name: bash
      if: runner.os != 'windows'
      run: mkdir toolchains
    - name: specify NDK
      if: runner.os != 'windows'
      uses: ravinderjangra/android-ndk-toolchain-setup@0.2
      with:
        api: '20'
        arch: 'arm'
        install-location: 'toolchains'
        force: true

    - name: Git submodule sync
      run: git submodule update --init

    - name: Grant execute permission for gradlew
      if: runner.os != 'windows'
      run: chmod +x gradlew
    - name: Build with Gradle
      if: runner.os != 'windows'
      run: |
        ./gradlew smarttubetv:clean --stacktrace
        ./gradlew smarttubetv:build --stacktrace
        ./gradlew smarttubetv:assembleDebug --stacktrace

    - name: Build with Gradle on Windows
      if: runner.os == 'windows'
      run: |
        .\gradlew.bat smarttubetv:clean --stacktrace
        .\gradlew.bat smarttubetv:build --stacktrace
        .\gradlew.bat smarttubetv:assembleDebug --stacktrace
