name: Android CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
  
    - uses: nttld/setup-ndk@v1
      with:
       ndk-version: r22b
       
    - name: Git submodule sync
      run: git submodule update --init

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew smarttubetv:assembleDebug --stacktrace
